name: CI

on: [push, pull_request]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Setup pnpm
      uses: pnpm/action-setup@v4.0.0
      with:
        version: latest
        run_install: true
    - name: Code style check
      run: pnpm fmt:check
    - name: Run tests
      run: pnpm test
  user_test:
    name: User Test
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        path: ./g-plane/typed-query-selector
    - name: Checkout "refined-github"
      uses: actions/checkout@v4
      with:
        repository: sindresorhus/refined-github
        ref: f462a67be700d790d5e4ea988479e0883d585e7d
        path: ./sindresorhus/refined-github
    - name: Install dependencies
      run: npm ci
      working-directory: ./sindresorhus/refined-github
    - name: Link package
      run: |
        cd ./g-plane/typed-query-selector
        sudo npm link
        cd ../../sindresorhus/refined-github
        npm link typed-query-selector
    - name: Execute in non-strict mode
      run: node node_modules/.bin/tsc --noEmit --extendedDiagnostics
      working-directory: ./sindresorhus/refined-github
    - name: Execute in strict mode
      run: |
        sed -i "s/typed-query-selector/typed-query-selector\/strict/" source/refined-github.ts
        node node_modules/.bin/tsc --noEmit --extendedDiagnostics
      working-directory: ./sindresorhus/refined-github
